# Generated by Django 5.2.1 on 2025-10-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='presence',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='emploidutemps',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='anneescolaire',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='certificatfrequentation',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='note',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='dossierinscriptionimage',
            name='ecole',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='specialite_matiere',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='classe',
            name='effectif',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='specialite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité/Matière principale'),
        ),
        migrations.DeleteModel(
            name='Ecole',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
