# Generated by Django 5.2.1 on 2025-10-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_etudiant_ecole_remove_paiement_ecole_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecolesettings',
            options={'ordering': ['nom_etablissement'], 'verbose_name': 'École', 'verbose_name_plural': 'Écoles'},
        ),
        migrations.RemoveField(
            model_name='ecolesettings',
            name='unique_instance',
        ),
        migrations.AlterField(
            model_name='ecolesettings',
            name='code_etablissement',
            field=models.CharField(blank=True, help_text='Code attribué par le ministère ou la direction académique', max_length=50, null=True, unique=True, verbose_name="Code de l'Établissement"),
        ),
    ]
