# Generated by Django 5.2.1 on 2025-10-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_anneescolaire_ecole_certificatfrequentation_ecole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='certificatfrequentation',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='dossierinscriptionimage',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='emploidutemps',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='note',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterField(
            model_name='programmematiere',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
    ]
