# Generated by Django 5.2.1 on 2025-10-22 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='dashboard.ecolesettings', verbose_name='École'),
        ),
    ]
