# Generated by Django 5.2.1 on 2025-10-22 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_enseignant_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard.etudiant'),
        ),
    ]
