# Generated by Django 5.2.1 on 2025-10-22 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_note_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='dashboard.etudiant'),
        ),
    ]
