# Generated by Django 5.2.1 on 2025-10-22 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_paiement_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='dashboard.etudiant'),
        ),
    ]
