# Generated by Django 5.2.1 on 2025-10-23 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_presence_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings'),
        ),
    ]
