# Generated by Django 5.2.1 on 2025-10-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_profile_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anneescolaire',
            name='active',
            field=models.BooleanField(default=False, help_text="Si cochée, cette année sera considérée comme l'année scolaire en cours.", verbose_name='Active (Année en cours)'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='annee',
            field=models.CharField(help_text='Exemple : 2024-2025', max_length=9, verbose_name='Année Scolaire'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together={('ecole', 'annee')},
        ),
    ]
