# Generated by Django 5.2.1 on 2025-10-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_anneescolaire_active_alter_anneescolaire_annee_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='anneescolaire',
            constraint=models.UniqueConstraint(fields=('ecole', 'annee'), name='unique_annee_par_ecole'),
        ),
    ]
