# Generated by Django 5.2.1 on 2025-10-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_anneescolaire_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='anneescolaire',
            name='unique_annee_par_ecole',
        ),
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together={('ecole', 'annee')},
        ),
    ]
