# Generated by Django 5.2.1 on 2025-10-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_anneescolaire_unique_annee_par_ecole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
    ]
