# Generated by Django 5.2.1 on 2025-10-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_paiement_ecole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='ecole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ecolesettings', verbose_name='École'),
        ),
    ]
