# Generated by Django 5.2.1 on 2025-10-24 03:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_paiement_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatfrequentation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificatfrequentation',
            name='lieu_delivrance',
            field=models.CharField(blank=True, default='Bamako', max_length=100, null=True, verbose_name='Lieu de délivrance'),
        ),
        migrations.AddField(
            model_name='certificatfrequentation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificatfrequentation',
            name='mention_legale',
            field=models.TextField(blank=True, null=True, verbose_name='Mention légale ou texte additionnel'),
        ),
    ]
