# Generated by Django 5.2.1 on 2025-10-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_certificatfrequentation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecolesettings',
            name='date_fin_essai',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Fin de la période d'essai gratuite"),
        ),
        migrations.AddField(
            model_name='ecolesettings',
            name='est_active',
            field=models.BooleanField(default=True, help_text="Indique si l'école peut utiliser le système", verbose_name='École active'),
        ),
        migrations.AlterField(
            model_name='certificatfrequentation',
            name='ministere',
            field=models.CharField(default='MINISTÈRE DE L’ENSEIGNEMENT SUPÉRIEUR / ET DE LA RECHERCHE SCIENTIFIQUE', max_length=255, verbose_name='Ministère de tutelle'),
        ),
    ]
